### ISSUE TITLE
Process condition

### ISSUE THREAD

**Issue by sforoushani** [nemocrys/multilog#18]
With the plan to transition to digital lab-books in mind, I suggest having the process condition tab as the landing page/tab, so we remember to fill in the info. I also suggest having no default values (or maybe NaN) to avoid confusion in case the fields are not filled in.

**Comment by arvedes** [comment]
Sounds good! We just need to rearrange the order of the devices in the config (put the ProcessConditionLogger in the first place).

In the config_template.yml I would keep the defaults to show that this is possible but we can comment them out - then the fileds are empty. Not sure if that works for the combo-boxes, though.
